// Translation dictionary for Categories
export const categoryTranslations: Record<string, string> = {
  "beauty": "Mỹ Phẩm & Làm Đẹp",
  "fragrances": "Nước Hoa Cao Cấp",
  "furniture": "Nội Thất & Gia Dụng",
  "groceries": "Thực Phẩm & Bách Hóa",
  "home-decoration": "Trang Trí Nhà Cửa",
  "kitchen-accessories": "Dụng Cụ Nhà Bếp",
  "laptops": "Máy Tính Xách Tay",
  "mens-shirts": "Áo Nam Thời Trang",
  "mens-shoes": "Giày Nam Cao Cấp",
  "mens-watches": "Đồng Hồ Nam Sang Trọng",
  "mobile-accessories": "Phụ Kiện Điện Thoại",
  "motorcycle": "Xe Máy & Phụ Tùng",
  "skin-care": "Chăm Sóc Da",
  "smartphones": "Điện Thoại Thông Minh",
  "sports-accessories": "Dụng Cụ Thể Thao",
  "sunglasses": "Kính Mát Thời Trang",
  "tops": "Áo Nữ Thời Trang",
  "vehicle": "Ô Tô & Phụ Tùng",
  "womens-bags": "Túi Xách Nữ",
  "womens-dresses": "Đầm Nữ Thời Trang",
  "womens-jewellery": "Trang Sức Nữ",
  "womens-shoes": "Giày Nữ Thời Trang",
  "womens-watches": "Đồng Hồ Nữ Cao Cấp",
};

// Vietnamese Product Translation details mapped by ID
export const productTranslations: Record<number, { title: string; description: string; brand?: string; warrantyInformation?: string; shippingInformation?: string }> = {
  1: {
    title: "Mascara Dày Cong Mi Essense Princess",
    description: "Mascara Essence Lash Princess giúp mi dài cong quyến rũ, không lem không trôi suốt cả ngày. Công thức thuần chay an toàn cho đôi mắt.",
    brand: "Essence",
    warrantyInformation: "Bảo hành đổi trả 7 ngày",
    shippingInformation: "Giao hàng nhanh 2-3 ngày",
  },
  2: {
    title: "Phấn Mắt 12 Màu Cao Cấp Eyeshadow Palette",
    description: "Bảng phấn mắt 12 màu kết hợp hạt nhũ mịn ánh kim. Chất phấn bám màu lâu trôi, lên màu chuẩn nét ngay từ lần quẹt đầu tiên.",
    brand: "Glamour Beauty",
    warrantyInformation: "Bảo hành 1 tháng",
    shippingInformation: "Giao hàng trong 1-2 ngày",
  },
  3: {
    title: "Phấn Phủ Dạng Bột Kiềm Dầu Mịn Màng",
    description: "Phấn phủ kiềm dầu chống bóng nhờn hiệu quả, che phủ lỗ chân lông và giữ lớp trang điểm bền màu tự nhiên suốt 12 giờ.",
    brand: "Velvet Touch",
    warrantyInformation: "Bảo hành 1 tháng",
    shippingInformation: "Giao hàng hỏa tốc trong ngày",
  },
  4: {
    title: "Son Mật Môi Dưỡng Ẩm Màu Đỏ Hồng",
    description: "Son thỏi dưỡng ẩm sâu với chiết xuất mật ong thiên nhiên, mang lại đôi môi căng mọng quyến rũ và tươi tắn.",
    brand: "Chic Gloss",
    warrantyInformation: "Đổi trả miễn phí 7 ngày",
    shippingInformation: "Giao hàng 2-3 ngày",
  },
  5: {
    title: "Sơn Mộc Móng Tay Sắc Đỏ Sang Trọng",
    description: "Sơn móng tay cao cấp lên màu nhanh khô, sáng bóng quyến rũ và không gây vàng móng. Thành phần an toàn tuyệt đối.",
    brand: "NailArt",
    warrantyInformation: "Bảo hành 1 tháng",
    shippingInformation: "Giao hàng nhanh trong ngày",
  },
  6: {
    title: "Nước Hoa Nữ Calvin Klein CK One 100ml",
    description: "Dòng nước hoa mang phong cách hiện đại, phóng khoáng với hương thơm hoa cỏ tự nhiên kết hợp gỗ tuyết tùng ấm áp.",
    brand: "Calvin Klein",
    warrantyInformation: "Cam kết chính hãng 100%",
    shippingInformation: "Miễn phí vận chuyển toàn quốc",
  },
  7: {
    title: "Nước Hoa Nam Dior Sauvage Eau De Parfum",
    description: "Mùi hương cuốn hút đỉnh cao cho nam giới với nốt hương cam Bergamot tươi mát quyện cùng hương gô tiêu đen nam tính.",
    brand: "Dior",
    warrantyInformation: "Cam kết chính hãng 100%",
    shippingInformation: "Giao hỏa tốc 2 giờ",
  },
  8: {
    title: "Nước Hoa Cao Cấp Chanel Coco Mademoiselle",
    description: "Hương thơm huyền thoại thể hiện sự sang trọng và quý phái của phái đẹp. Sự kết hợp giữa hoa hồng, hoa nhài và hoắc hương.",
    brand: "Chanel",
    warrantyInformation: "Bảo hành chính hãng 12 tháng",
    shippingInformation: "Giao hàng nhanh 1-2 ngày",
  },
  9: {
    title: "Nước Hoa Nữ Gucci Bloom Eau De Parfum",
    description: "Tỏa ngát hương hoa tự nhiên với hoa huệ trắng và hoa nhài Ý. Phong cách thanh lịch và dịu dàng tôn vinh nét nữ tính.",
    brand: "Gucci",
    warrantyInformation: "Cam kết chính hãng 100%",
    shippingInformation: "Giao hàng trong 2-3 ngày",
  },
  10: {
    title: "Ghế Sofa Bọc Da Bò Cao Cấp Scandinavian",
    description: "Ghế sofa 3 chỗ ngồi khung gỗ tự nhiên chống mối mọt, bọc da bò nhập khẩu mềm mại, tôn vinh không gian phòng khách hiện đại.",
    brand: "Nordic Living",
    warrantyInformation: "Bảo hành khung 5 năm",
    shippingInformation: "Miễn phí vận chuyển & lắp đặt",
  },
  11: {
    title: "Bàn Làm Việc Gỗ Sồi Tự Nhiên Hiện Đại",
    description: "Bàn làm việc gỗ sồi nguyên khối chống cong vênh, tích hợp ngăn kéo thông minh và hệ thống đi dây điện gọn gàng.",
    brand: "Modern Wood",
    warrantyInformation: "Bảo hành 2 năm",
    shippingInformation: "Giao hàng & lắp đặt tận nơi",
  },
  12: {
    title: "Ghế Xoay Văn Phòng Công Thái Học Ergonomic",
    description: "Ghế công thái học hỗ trợ cột sống nâng đỡ thắt lưng tuyệt đối, lưới thoáng khí cao cấp chống đọng mồ hôi hiệu quả.",
    brand: "ErgoChair",
    warrantyInformation: "Bảo hành 3 năm chính hãng",
    shippingInformation: "Giao hàng nhanh trong 24 giờ",
  },
  13: {
    title: "Giường Ngủ Gỗ Sồi Cao Cấp Kiểu Nhật 1.8m",
    description: "Giường ngủ phong cách tối giản kiểu Nhật Bản, chất liệu gỗ sồi tự nhiên được xử lý chống ẩm mốc và mối mọt tối đa.",
    brand: "Zen Home",
    warrantyInformation: "Bảo hành 5 năm",
    shippingInformation: "Vận chuyển và lắp đặt miễn phí",
  },
  14: {
    title: "Tủ Quần Áo 4 Cánh Gỗ Công Nghiệp An Cường",
    description: "Tủ quần áo hiện đại thiết kế kịch trần, nhiều ngăn chứa đồ tiện lợi, bản lề giảm chấn êm ái chống ồn.",
    brand: "An Cường",
    warrantyInformation: "Bảo hành 2 năm",
    shippingInformation: "Lắp đặt tận nhà",
  },
  15: {
    title: "Táo Đỏ Hữu Cơ Nhập Khẩu Mỹ (1kg)",
    description: "Táo đỏ tươi ngọt tự nhiên, giòn tan đậm vị, giàu vitamin C và chất xơ tốt cho sức khỏe cả gia đình.",
    brand: "Fresh Orchard",
    warrantyInformation: "Đổi trả nếu không tươi ngon",
    shippingInformation: "Giao hàng lạnh hỏa tốc",
  },
  16: {
    title: "Thịt Bò Mỹ Nhập Khẩu Thượng Hạng (500g)",
    description: "Thịt thăn bò Mỹ thái sẵn cho món lẩu và nướng. Vân mỡ mềm mại tự nhiên, mọng nước và ngọt vị.",
    brand: "US Beef Prime",
    warrantyInformation: "Đảm bảo an toàn thực phẩm 100%",
    shippingInformation: "Giao hàng trong túi giữ nhiệt 2h",
  },
  17: {
    title: "Sữa Tươi Tiệt Trùng Hữu Cơ Nguyên Chất 1L",
    description: "Sữa tươi organic nhập khẩu từ trang trại chuẩn Châu Âu, giữ trọn hương vị thơm béo và dưỡng chất tự nhiên.",
    brand: "BioMilk",
    warrantyInformation: "Đổi mới nếu hỏng vỏ hộp",
    shippingInformation: "Giao hàng nhanh 2-3 ngày",
  },
  18: {
    title: "Hạt Óc Chó Mỹ Tách Vỏ Hữu Cơ 500g",
    description: "Hạt óc chó sấy giòn béo thơm, giàu Omega-3 tốt cho trí não và sức khỏe tim mạch.",
    brand: "Nutty Health",
    warrantyInformation: "Đổi trả 7 ngày",
    shippingInformation: "Giao hàng toàn quốc",
  },
  19: {
    title: "Dầu Ăn Olive Nguyên Chất Extra Virgin 750ml",
    description: "Dầu ô liu ép lạnh nguyên chất nhập khẩu từ Địa Trung Hải, lý tưởng cho món salad và nấu ăn lành mạnh.",
    brand: "Borges",
    warrantyInformation: "Cam kết chính hãng",
    shippingInformation: "Giao hàng nhanh 1-2 ngày",
  },
  20: {
    title: "Đèn Thả Trần Trang Trí Hiện Đại Bắc Âu",
    description: "Đèn thả trần phong cách Scandinavian tỏa ánh sáng vàng ấm áp, tạo điểm nhấn sang trọng cho bàn ăn và phòng khách.",
    brand: "LumiDecor",
    warrantyInformation: "Bảo hành 12 tháng",
    shippingInformation: "Giao hàng toàn quốc",
  },
  21: {
    title: "Đồng Hồ Treo Tường Gỗ Tự Nhiên Tối Giản",
    description: "Đồng hồ treo tường máy kim trôi êm ái không gây tiếng động, thiết kế gỗ sồi sang trọng cho mọi không gian.",
    brand: "ClockArt",
    warrantyInformation: "Bảo hành bộ máy 2 năm",
    shippingInformation: "Giao nhanh 1-2 ngày",
  },
  22: {
    title: "Thảm Trải Sàn Lông Cừu Nhân Tạo Mềm Mại",
    description: "Thảm trang trí sàn phòng khách 1.6m x 2m chống trượt tuyệt đối, chất lông cừu êm ái tôn lên nét sang trọng.",
    brand: "SoftRug",
    warrantyInformation: "Bảo hành 1 năm",
    shippingInformation: "Giao hàng tận nhà",
  },
  23: {
    title: "Bộ Nồi Inox 5 Đáy Cao Cấp Chống Dính",
    description: "Bộ 3 nồi inox 304 tiêu chuẩn Đức, sử dụng linh hoạt trên mọi loại bếp kể từ bếp từ, bếp hồng ngoại.",
    brand: "CookMaster",
    warrantyInformation: "Bảo hành 5 năm",
    shippingInformation: "Miễn phí vận chuyển",
  },
  24: {
    title: "Chảo Chống Dính Đá Hoa Cương 28cm",
    description: "Chảo đá hoa cương phủ men chống dính siêu bền, không giải phóng PFOA an toàn tuyệt đối cho sức khỏe.",
    brand: "ChefChoice",
    warrantyInformation: "Bảo hành 2 năm",
    shippingInformation: "Giao nhanh 24h",
  },
  25: {
    title: "Dao Bếp Nhật Bản Steel VG10 Nguyên Khối",
    description: "Dao thái làm từ thép Nhật Bản sắc bén gấp 5 lần dao thường, thiết kế cán gỗ hồng sắc chống trượt.",
    brand: "Katai Knife",
    warrantyInformation: "Bảo hành trọn đời bộ lưỡi",
    shippingInformation: "Giao hỏa tốc toàn quốc",
  },
  26: {
    title: "Laptop Apple MacBook Pro 16 inch M3 Max",
    description: "Siêu máy tính xách tay với chip M3 Max cực khủng, RAM 36GB, SSD 1TB, màn hình Liquid Retina XDR sắc nét đỉnh cao.",
    brand: "Apple",
    warrantyInformation: "Bảo hành 12 tháng Apple Care",
    shippingInformation: "Miễn phí giao hàng hỏa tốc",
  },
  27: {
    title: "Laptop Dell XPS 15 Intel Core i9 RAM 32GB",
    description: "Dòng laptop đồ họa cao cấp màn hình 4K OLED cảm ứng, vỏ nhôm nguyên khối sang trọng cùng hiệu năng vượt trội.",
    brand: "Dell",
    warrantyInformation: "Bảo hành tận nơi 24 tháng",
    shippingInformation: "Giao hàng trong ngày",
  },
  28: {
    title: "Laptop Gaming ASUS ROG Strix G16 RTX 4080",
    description: "Laptop chơi game đỉnh cao màn hình 240Hz siêu mượt, chip Intel i9 thế hệ 14 kèm cạc đồ họa RTX 4080 cân mọi tựa game AAA.",
    brand: "ASUS",
    warrantyInformation: "Bảo hành 24 tháng chính hãng",
    shippingInformation: "Tặng kèm quà tặng gaming",
  },
  29: {
    title: "Laptop Lenovo ThinkPad X1 Carbon Gen 11",
    description: "Huyền thoại laptop doanh nhân mỏng nhẹ chỉ 1.1kg, chất liệu sợi carbon siêu bền bỉ và bàn phím gõ êm nhất thế giới.",
    brand: "Lenovo",
    warrantyInformation: "Bảo hành 3 năm Premier Support",
    shippingInformation: "Giao hàng nhanh 24h",
  },
  30: {
    title: "Áo Sơ Mi Nam Tay Dài Chống Nhăn Premium",
    description: "Áo sơ mi nam chất liệu vải sợi tre Bamboo thoáng mát, phom dáng Slim-fit ôm gọn vừa vặn tôn nét lịch lãm.",
    brand: "ManStyle",
    warrantyInformation: "Đổi trả 14 ngày",
    shippingInformation: "Giao hàng 2-3 ngày",
  },
  31: {
    title: "Áo Polo Nam Co Giãn 4 Chiều Thoáng Khí",
    description: "Áo thun Polo nam sợi cotton xuất khẩu co giãn mềm mại, thấm hút mồ hôi vượt trội thích hợp mặc hàng ngày.",
    brand: "ManStyle",
    warrantyInformation: "Đổi trả 7 ngày",
    shippingInformation: "Giao hàng toàn quốc",
  },
  32: {
    title: "Giày Tây Nam Da Bò Thật Oxford Lịch Lãm",
    description: "Giày da nam gia công thủ công từ da bò nguyên miếng sang trọng, đế cao su chống đúc êm chân vững chãi.",
    brand: "Royal Leather",
    warrantyInformation: "Bảo hành da 12 tháng",
    shippingInformation: "Cho thử hàng trước khi thanh toán",
  },
  33: {
    title: "Giày Sneaker Nam Thể Thao Năng Động",
    description: "Giày thể thao nam siêu nhẹ độ đàn hồi cao, đế cao su tổng hợp bám dính tốt phù hợp tập luyện và đi chơi.",
    brand: "SportPro",
    warrantyInformation: "Bảo hành keo 6 tháng",
    shippingInformation: "Giao nhanh 1-2 ngày",
  },
  34: {
    title: "Đồng Hồ Nam Cơ Tự Động Rolex Submariner",
    description: "Đồng hồ nam dây thép không gỉ 316L, mặt kính Sapphire chống xước tuyệt đối và khả năng chống nước 300m.",
    brand: "Rolex",
    warrantyInformation: "Bảo hành quốc tế 5 năm",
    shippingInformation: "Giao hàng bảo đảm cao cấp",
  },
  35: {
    title: "Đồng Hồ Nam dây Da Seiko Presage Automatic",
    description: "Đồng hồ cơ Nhật Bản mặt số hoạ tiết chải tia tuyệt đẹp, dây da calfskin mềm mại ôm tay tinh tế.",
    brand: "Seiko",
    warrantyInformation: "Bảo hành chính hãng 3 năm",
    shippingInformation: "Giao hàng nhanh toàn quốc",
  },
  36: {
    title: "Củ Sạc Nhanh Anker 65W GaN Prime 3 Cổng",
    description: "Sạc nhanh công nghệ GaN nhỏ gọn sạc đồng thời MacBook, iPhone và iPad với công suất tối đa 65W an toàn.",
    brand: "Anker",
    warrantyInformation: "Bảo hành 18 tháng 1 đổi 1",
    shippingInformation: "Giao nhanh 2h",
  },
  37: {
    title: "Xe Máy Vespa Sprint S 125cc Phiên Bản Đặc Biệt",
    description: "Dòng xe tay ga Ý biểu tượng phong cách trẻ trung cá tính, trang bị phanh ABS an toàn và động cơ i-Get êm ái.",
    brand: "Vespa",
    warrantyInformation: "Bảo hành 3 năm hoặc 30.000km",
    shippingInformation: "Hỗ trợ giao xe tận nhà",
  },
  38: {
    title: "Tinh Chất Serum Chăm Sóc Da Estée Lauder Advanced Night Repair",
    description: "Serum phục hồi da đêm bán chạy số 1 thế giới giúp chống lão hóa, làm mờ nếp nhăn và cho làn da căng bóng mịn màng.",
    brand: "Estée Lauder",
    warrantyInformation: "Cam kết chính hãng 100%",
    shippingInformation: "Giao nhanh 1-2 ngày",
  },
  39: {
    title: "Điện Thoại Apple iPhone 15 Pro Max 256GB Titanium",
    description: "Siêu phẩm điện thoại khung vỏ Titanium vũ trụ mỏng nhẹ, chip A17 Pro mạnh mẽ nhất và camera Zoom quang học 5x.",
    brand: "Apple",
    warrantyInformation: "Bảo hành 12 tháng Apple Việt Nam",
    shippingInformation: "Giao hàng hỏa tốc 2 giờ",
  },
  40: {
    title: "Điện Thoại Samsung Galaxy S24 Ultra AI 512GB",
    description: "Điện thoại trang bị trí tuệ nhân tạo Galaxy AI đột phá, bút S-Pen quyền năng và camera 200MP chụp đêm ấn tượng.",
    brand: "Samsung",
    warrantyInformation: "Bảo hành 12 tháng chính hãng",
    shippingInformation: "Giao hàng hỏa tốc toàn quốc",
  },
};
